/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Session
         * @description Who is signed in, the UI language, and everything the shell draws from: the
         *     module switches, the navigation built from them, the rail's status card.
         */
        get: operations["read_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ConflictBody
         * @description 409 — a ``block`` rule fired; repeat the write with ``override`` to keep it.
         */
        ConflictBody: {
            /**
             * Error
             * @constant
             */
            error: "conflict";
            /** Violations */
            violations: components["schemas"]["ViolationBody"][];
        };
        /**
         * InvalidBody
         * @description 400 — a service refused the values (its ``ValueError`` message).
         */
        InvalidBody: {
            /**
             * Error
             * @constant
             */
            error: "invalid";
            /** Message */
            message: string;
        };
        /** Nav */
        Nav: {
            /** Bottom Slots */
            bottom_slots: components["schemas"]["NavSlot"][];
            /** Items */
            items: components["schemas"]["NavItem"][];
            /** More Routes */
            more_routes: string[];
            /** More Rubrics */
            more_rubrics: string[];
        };
        /**
         * NavItem
         * @description One section in the rail, in rail order. Its label is ``nav.<key>`` and its
         *     rubric's is ``masthead.rubric.<rubric>``; both live in the i18n dictionaries.
         */
        NavItem: {
            /** Eyebrow */
            eyebrow: string;
            /** Key */
            key: string;
            /** Route */
            route: string;
            /** Rubric */
            rubric: string;
        };
        /**
         * NavSlot
         * @description One of the three middle columns of the phone's bottom bar.
         */
        NavSlot: {
            /** Icon */
            icon: string;
            /** Key */
            key: string;
            /** Label Key */
            label_key: string;
            /** Route */
            route: string;
            /** Routes */
            routes: string[];
        };
        /**
         * NotFoundBody
         * @description 404 — the module behind the endpoint is switched off, or nothing is there.
         */
        NotFoundBody: {
            /**
             * Error
             * @enum {string}
             */
            error: "module_disabled" | "not_found";
        };
        /**
         * RailStat
         * @description One row of the rail's status card, as values — the client phrases them.
         *     Only the fields of the row's own ``key`` are filled; the rest are null.
         */
        RailStat: {
            /** Calories */
            calories: number | null;
            /** Calories Max */
            calories_max: number | null;
            /** Days Since */
            days_since: number | null;
            /** Delta Kg */
            delta_kg: number | null;
            /**
             * Key
             * @enum {string}
             */
            key: "weight" | "recovery" | "nutrition" | "workouts";
            /** Protein G */
            protein_g: number | null;
            /** Readiness */
            readiness: number | null;
            /** Sleep Seconds */
            sleep_seconds: number | null;
            /**
             * Tone
             * @enum {string}
             */
            tone: "" | "good" | "bad" | "warn";
            /** Weight Kg */
            weight_kg: number | null;
        };
        /** SessionView */
        SessionView: {
            /** Enabled Modules */
            enabled_modules: {
                [key: string]: boolean;
            };
            /**
             * Lang
             * @enum {string}
             */
            lang: "en" | "ru";
            nav: components["schemas"]["Nav"];
            /** Rail */
            rail: components["schemas"]["RailStat"][];
            /** Username */
            username: string;
        };
        /**
         * UnauthenticatedBody
         * @description 401 — no valid session cookie.
         */
        UnauthenticatedBody: {
            /**
             * Error
             * @constant
             */
            error: "unauthenticated";
        };
        /**
         * ViolationBody
         * @description One rule a write tripped — ``Violation.to_dict()`` of the conflict engine.
         */
        ViolationBody: {
            /** Category */
            category: string | null;
            /** Domain A */
            domain_a: string;
            /** Domain B */
            domain_b: string;
            /** Evidence */
            evidence: string | null;
            /** Message */
            message: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Rule Id */
            rule_id: number | null;
            /** Rule Type */
            rule_type: string;
            /** Severity */
            severity: string;
            /** Source */
            source: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthenticatedBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundBody"];
                };
            };
        };
    };
}

// openapi.json sha256: 1e113bf0ff4bda86da895ecff945bba8aef6496ccae77fa7064253677b256260
