/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Session
         * @description Who is signed in, the UI language, and everything the shell draws from: the
         *     module switches, the navigation built from them, the rail's status card.
         */
        get: operations["read_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Today
         * @description The whole Today screen in one request: figures, the week's changes, the day's
         *     feed, what needs attention and the goal. A module that is switched off
         *     contributes nothing: no calories or meals without nutrition, no timeline rows
         *     without the timeline.
         */
        get: operations["read_today"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weight/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Weight Log
         * @description Log a weight as a manual reading. A reading the day already holds comes back
         *     with ``created: false``; a block rule answers 409 until ``override`` is set.
         */
        post: operations["create_weight_log"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weight/logs/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Weight Log
         * @description Take a reading back. If it was the day's active one, the reading it had
         *     outranked (a Garmin import) becomes active again.
         */
        delete: operations["delete_weight_log"];
        options?: never;
        head?: never;
        /**
         * Update Weight Log
         * @description Correct a reading; whatever the body leaves out stays as it was.
         */
        patch: operations["update_weight_log"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttentionItem */
        AttentionItem: {
            /** Domain */
            domain: string | null;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "note" | "info" | "warn" | "block";
        };
        /**
         * ConflictBody
         * @description 409 — a ``block`` rule fired; repeat the write with ``override`` to keep it.
         */
        ConflictBody: {
            /**
             * Error
             * @constant
             */
            error: "conflict";
            /** Violations */
            violations: components["schemas"]["ViolationBody"][];
        };
        /**
         * Corridor
         * @description A band a value is read against.
         */
        Corridor: {
            /** Hi */
            hi: number;
            /** Lo */
            lo: number;
        };
        /**
         * FeedRow
         * @description One line of the day. ``text`` and ``detail`` are the owner's own words where
         *     ``kind`` is an event or a signal; for the rest the client writes them from
         *     ``kind`` and ``value``.
         */
        FeedRow: {
            /** Detail */
            detail: string;
            /**
             * Dot
             * @enum {string}
             */
            dot: "good" | "cool" | "violet" | "amber";
            /**
             * Kind
             * @enum {string}
             */
            kind: "event" | "meal" | "signal" | "brief" | "weight";
            /** Text */
            text: string;
            /** Time */
            time: string;
            /** Value */
            value: number | null;
        };
        /**
         * Goal
         * @description The first active weight goal, with where he started.
         */
        Goal: {
            /** Current Kg */
            current_kg: number;
            /** Deadline */
            deadline: string | null;
            forecast: components["schemas"]["GoalForecast"] | null;
            /** Name */
            name: string;
            /** Start Kg */
            start_kg: number;
            /** Target Kg */
            target_kg: number;
        };
        /**
         * GoalForecast
         * @description Where the present trend meets the goal.
         */
        GoalForecast: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Days Ahead */
            days_ahead: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InvalidBody
         * @description 400 — a service refused the values (its ``ValueError`` message).
         */
        InvalidBody: {
            /**
             * Error
             * @constant
             */
            error: "invalid";
            /** Message */
            message: string;
        };
        /** LatestWeight */
        LatestWeight: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Kg */
            kg: number;
        };
        /** Nav */
        Nav: {
            /** Bottom Slots */
            bottom_slots: components["schemas"]["NavSlot"][];
            /** Items */
            items: components["schemas"]["NavItem"][];
            /** More Routes */
            more_routes: string[];
            /** More Rubrics */
            more_rubrics: string[];
        };
        /**
         * NavItem
         * @description One section in the rail, in rail order. Its label is ``nav.<key>`` and its
         *     rubric's is ``masthead.rubric.<rubric>``; both live in the i18n dictionaries.
         */
        NavItem: {
            /** Eyebrow */
            eyebrow: string;
            /** Key */
            key: string;
            /** Route */
            route: string;
            /** Rubric */
            rubric: string;
        };
        /**
         * NavSlot
         * @description One of the three middle columns of the phone's bottom bar.
         */
        NavSlot: {
            /** Icon */
            icon: string;
            /** Key */
            key: string;
            /** Label Key */
            label_key: string;
            /** Route */
            route: string;
            /** Routes */
            routes: string[];
        };
        /**
         * NotFoundBody
         * @description 404 — the module behind the endpoint is switched off, or nothing is there.
         */
        NotFoundBody: {
            /**
             * Error
             * @enum {string}
             */
            error: "module_disabled" | "not_found";
        };
        /**
         * RailStat
         * @description One row of the rail's status card, as values — the client phrases them.
         *     Only the fields of the row's own ``key`` are filled; the rest are null.
         */
        RailStat: {
            /** Calories */
            calories: number | null;
            /** Calories Max */
            calories_max: number | null;
            /** Days Since */
            days_since: number | null;
            /** Delta Kg */
            delta_kg: number | null;
            /**
             * Key
             * @enum {string}
             */
            key: "weight" | "recovery" | "nutrition" | "workouts";
            /** Protein G */
            protein_g: number | null;
            /** Readiness */
            readiness: number | null;
            /** Sleep Seconds */
            sleep_seconds: number | null;
            /**
             * Tone
             * @enum {string}
             */
            tone: "" | "good" | "bad" | "warn";
            /** Weight Kg */
            weight_kg: number | null;
        };
        /** SessionView */
        SessionView: {
            /** Enabled Modules */
            enabled_modules: {
                [key: string]: boolean;
            };
            /**
             * Lang
             * @enum {string}
             */
            lang: "en" | "ru";
            nav: components["schemas"]["Nav"];
            /** Rail */
            rail: components["schemas"]["RailStat"][];
            /** Username */
            username: string;
        };
        /**
         * SyncStamp
         * @description An integration that last put something in the lake, and the day it did.
         */
        SyncStamp: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Source */
            source: string;
        };
        /**
         * TodayFigure
         * @description One of the key figures. Only the fields of its own ``key`` are filled; the rest
         *     are null. ``value`` is null until there is a reading, and the row stays.
         */
        TodayFigure: {
            /** Baseline */
            baseline: number | null;
            corridor: components["schemas"]["Corridor"] | null;
            /** Gained */
            gained: number | null;
            /**
             * Key
             * @enum {string}
             */
            key: "weight" | "sleep_score" | "hrv_avg" | "body_battery_high" | "calories";
            /** Sleep Seconds */
            sleep_seconds: number | null;
            /** Trend */
            trend: number | null;
            /** Value */
            value: number | null;
        };
        /** TodayView */
        TodayView: {
            /** Attention */
            attention: components["schemas"]["AttentionItem"][];
            /** Changes */
            changes: components["schemas"]["WeekChange"][];
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Feed */
            feed: components["schemas"]["FeedRow"][];
            /** Figures */
            figures: components["schemas"]["TodayFigure"][];
            goal: components["schemas"]["Goal"] | null;
            latest_weight: components["schemas"]["LatestWeight"] | null;
            /** Narrative */
            narrative: string;
            /**
             * Narrative Source
             * @enum {string}
             */
            narrative_source: "digest" | "computed";
            /** Sync */
            sync: components["schemas"]["SyncStamp"][];
        };
        /**
         * UnauthenticatedBody
         * @description 401 — no valid session cookie.
         */
        UnauthenticatedBody: {
            /**
             * Error
             * @constant
             */
            error: "unauthenticated";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ViolationBody
         * @description One rule a write tripped — ``Violation.to_dict()`` of the conflict engine.
         */
        ViolationBody: {
            /** Category */
            category: string | null;
            /** Domain A */
            domain_a: string;
            /** Domain B */
            domain_b: string;
            /** Evidence */
            evidence: string | null;
            /** Message */
            message: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /** Rule Id */
            rule_id: number | null;
            /** Rule Type */
            rule_type: string;
            /** Severity */
            severity: string;
            /** Source */
            source: string | null;
        };
        /**
         * WeekChange
         * @description A metric this week against last: the two seven-day values, on the corridor of
         *     his own norm where there is one.
         */
        WeekChange: {
            /** After */
            after: number;
            /** Before */
            before: number;
            /**
             * Domain Key
             * @enum {string}
             */
            domain_key: "weight" | "garmin" | "nutrition";
            /** Hi */
            hi: number | null;
            /**
             * Key
             * @enum {string}
             */
            key: "weight" | "sleep_score" | "hrv_avg" | "body_battery_high" | "calories";
            /** Lo */
            lo: number | null;
            /**
             * Tone
             * @enum {string}
             */
            tone: "" | "good" | "bad";
        };
        /** WeightLogCreate */
        WeightLogCreate: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Note */
            note?: string | null;
            /**
             * Override
             * @default false
             */
            override: boolean;
            /** Weight Kg */
            weight_kg: number;
        };
        /** WeightLogCreated */
        WeightLogCreated: {
            /** Created */
            created: boolean;
            /** Id */
            id: number;
        };
        /**
         * WeightLogPatch
         * @description What to change; what is left out stays. ``note`` is the one field where an
         *     explicit ``null`` means something: it clears the note.
         */
        WeightLogPatch: {
            /** Date */
            date?: string | null;
            /** Note */
            note?: string | null;
            /**
             * Override
             * @default false
             */
            override: boolean;
            /** Weight Kg */
            weight_kg?: number | null;
        };
        /**
         * WeightLogRef
         * @description The row a write ended up on. Moving a reading to another day makes a new row,
         *     so a patch answers with the id to use from then on.
         */
        WeightLogRef: {
            /** Id */
            id: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthenticatedBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundBody"];
                };
            };
        };
    };
    read_today: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayView"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthenticatedBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundBody"];
                };
            };
        };
    };
    create_weight_log: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeightLogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeightLogCreated"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthenticatedBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_weight_log: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthenticatedBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_weight_log: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeightLogPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeightLogRef"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidBody"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnauthenticatedBody"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundBody"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictBody"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}

// openapi.json sha256: 7e7ab3c5a0e8c9db6dd767e9bb60186487a41cb677b5a5b460ddda2ec5bb1a94
